/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SlimPlaygroundSidebarItem } from "./components/slim-playground-sidebar/slim-playground-sidebar";
export { SlimPlaygroundSidebarItem } from "./components/slim-playground-sidebar/slim-playground-sidebar";
export namespace Components {
    interface SlimAlert {
        "heading"?: string;
        /**
          * @default "info"
         */
        "variant": "info" | "success" | "warning" | "danger";
    }
    interface SlimBadge {
        /**
          * @default "md"
         */
        "size": "sm" | "md";
        /**
          * @default "neutral"
         */
        "variant": "neutral" | "primary" | "success" | "warning" | "danger";
    }
    interface SlimButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary" | "danger" | "ghost";
    }
    interface SlimCheckbox {
        "checkboxId"?: string;
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        /**
          * @default false
         */
        "required": boolean;
        "value"?: string;
    }
    interface SlimInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "error"?: string;
        "hint"?: string;
        "inputId"?: string;
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default "text"
         */
        "type": "text" | "email" | "password" | "tel" | "number";
        /**
          * @default ""
         */
        "value": string;
    }
    interface SlimModal {
        /**
          * Optional modal title
         */
        "heading"?: string;
        /**
          * Whether the modal is open
          * @default false
         */
        "open": boolean;
    }
    interface SlimPlaygroundSidebar {
        /**
          * Currently active item id.
         */
        "active"?: string;
        /**
          * Whether the sidebar is collapsed (icon-only rail).
          * @default false
         */
        "collapsed": boolean;
        /**
          * Show/hide the collapse toggle button.
          * @default true
         */
        "collapsible": boolean;
        /**
          * Sidebar heading shown in the header.
          * @default "Components"
         */
        "heading": string;
        /**
          * Menu items to render.
          * @default []
         */
        "items": SlimPlaygroundSidebarItem[];
        /**
          * @default 24
         */
        "pinnedBottom": number;
        /**
          * @default 24
         */
        "pinnedLeft": number;
        /**
          * Fixed positioning offsets (in px).
          * @default 24
         */
        "pinnedTop": number;
    }
    interface SlimSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        /**
          * @default []
         */
        "options": { value: string; label: string; disabled?: boolean }[];
        /**
          * @default false
         */
        "required": boolean;
        "selectId"?: string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface SlimSwitch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        /**
          * @default false
         */
        "required": boolean;
        "switchId"?: string;
    }
    interface SlimTextarea {
        /**
          * @default false
         */
        "disabled": boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "maxlength"?: number;
        "minlength"?: number;
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 4
         */
        "rows": number;
        "textareaId"?: string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface SlimTooltip {
        /**
          * Disables showing the tooltip via interactions.
          * @default false
         */
        "disabled": boolean;
        /**
          * Max width of the tooltip bubble, in pixels.
          * @default 240
         */
        "maxWidth": number;
        /**
          * Pixel offset between trigger and tooltip bubble.
          * @default 8
         */
        "offset": number;
        /**
          * Controls tooltip visibility. Can be toggled by hover/focus by default.
          * @default false
         */
        "open": boolean;
        /**
          * Where the tooltip appears relative to the trigger.
          * @default "top"
         */
        "placement": Placement;
        /**
          * Tooltip text. If omitted, the default slot is used as tooltip content.
         */
        "text"?: string;
    }
}
export interface SlimCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimCheckboxElement;
}
export interface SlimInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimInputElement;
}
export interface SlimModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimModalElement;
}
export interface SlimPlaygroundSidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimPlaygroundSidebarElement;
}
export interface SlimSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimSelectElement;
}
export interface SlimSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimSwitchElement;
}
export interface SlimTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimTextareaElement;
}
export interface SlimTooltipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlimTooltipElement;
}
declare global {
    interface HTMLSlimAlertElement extends Components.SlimAlert, HTMLStencilElement {
    }
    var HTMLSlimAlertElement: {
        prototype: HTMLSlimAlertElement;
        new (): HTMLSlimAlertElement;
    };
    interface HTMLSlimBadgeElement extends Components.SlimBadge, HTMLStencilElement {
    }
    var HTMLSlimBadgeElement: {
        prototype: HTMLSlimBadgeElement;
        new (): HTMLSlimBadgeElement;
    };
    interface HTMLSlimButtonElement extends Components.SlimButton, HTMLStencilElement {
    }
    var HTMLSlimButtonElement: {
        prototype: HTMLSlimButtonElement;
        new (): HTMLSlimButtonElement;
    };
    interface HTMLSlimCheckboxElementEventMap {
        "slimChange": boolean;
    }
    interface HTMLSlimCheckboxElement extends Components.SlimCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimCheckboxElementEventMap>(type: K, listener: (this: HTMLSlimCheckboxElement, ev: SlimCheckboxCustomEvent<HTMLSlimCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimCheckboxElementEventMap>(type: K, listener: (this: HTMLSlimCheckboxElement, ev: SlimCheckboxCustomEvent<HTMLSlimCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimCheckboxElement: {
        prototype: HTMLSlimCheckboxElement;
        new (): HTMLSlimCheckboxElement;
    };
    interface HTMLSlimInputElementEventMap {
        "slimChange": string;
    }
    interface HTMLSlimInputElement extends Components.SlimInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimInputElementEventMap>(type: K, listener: (this: HTMLSlimInputElement, ev: SlimInputCustomEvent<HTMLSlimInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimInputElementEventMap>(type: K, listener: (this: HTMLSlimInputElement, ev: SlimInputCustomEvent<HTMLSlimInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimInputElement: {
        prototype: HTMLSlimInputElement;
        new (): HTMLSlimInputElement;
    };
    interface HTMLSlimModalElementEventMap {
        "slimClose": void;
    }
    interface HTMLSlimModalElement extends Components.SlimModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimModalElementEventMap>(type: K, listener: (this: HTMLSlimModalElement, ev: SlimModalCustomEvent<HTMLSlimModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimModalElementEventMap>(type: K, listener: (this: HTMLSlimModalElement, ev: SlimModalCustomEvent<HTMLSlimModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimModalElement: {
        prototype: HTMLSlimModalElement;
        new (): HTMLSlimModalElement;
    };
    interface HTMLSlimPlaygroundSidebarElementEventMap {
        "slimSelect": string;
        "slimToggle": boolean;
    }
    interface HTMLSlimPlaygroundSidebarElement extends Components.SlimPlaygroundSidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimPlaygroundSidebarElementEventMap>(type: K, listener: (this: HTMLSlimPlaygroundSidebarElement, ev: SlimPlaygroundSidebarCustomEvent<HTMLSlimPlaygroundSidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimPlaygroundSidebarElementEventMap>(type: K, listener: (this: HTMLSlimPlaygroundSidebarElement, ev: SlimPlaygroundSidebarCustomEvent<HTMLSlimPlaygroundSidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimPlaygroundSidebarElement: {
        prototype: HTMLSlimPlaygroundSidebarElement;
        new (): HTMLSlimPlaygroundSidebarElement;
    };
    interface HTMLSlimSelectElementEventMap {
        "slimChange": string;
    }
    interface HTMLSlimSelectElement extends Components.SlimSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimSelectElementEventMap>(type: K, listener: (this: HTMLSlimSelectElement, ev: SlimSelectCustomEvent<HTMLSlimSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimSelectElementEventMap>(type: K, listener: (this: HTMLSlimSelectElement, ev: SlimSelectCustomEvent<HTMLSlimSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimSelectElement: {
        prototype: HTMLSlimSelectElement;
        new (): HTMLSlimSelectElement;
    };
    interface HTMLSlimSwitchElementEventMap {
        "slimChange": boolean;
    }
    interface HTMLSlimSwitchElement extends Components.SlimSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimSwitchElementEventMap>(type: K, listener: (this: HTMLSlimSwitchElement, ev: SlimSwitchCustomEvent<HTMLSlimSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimSwitchElementEventMap>(type: K, listener: (this: HTMLSlimSwitchElement, ev: SlimSwitchCustomEvent<HTMLSlimSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimSwitchElement: {
        prototype: HTMLSlimSwitchElement;
        new (): HTMLSlimSwitchElement;
    };
    interface HTMLSlimTextareaElementEventMap {
        "slimChange": string;
    }
    interface HTMLSlimTextareaElement extends Components.SlimTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimTextareaElementEventMap>(type: K, listener: (this: HTMLSlimTextareaElement, ev: SlimTextareaCustomEvent<HTMLSlimTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimTextareaElementEventMap>(type: K, listener: (this: HTMLSlimTextareaElement, ev: SlimTextareaCustomEvent<HTMLSlimTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimTextareaElement: {
        prototype: HTMLSlimTextareaElement;
        new (): HTMLSlimTextareaElement;
    };
    interface HTMLSlimTooltipElementEventMap {
        "slimShow": void;
        "slimHide": void;
    }
    interface HTMLSlimTooltipElement extends Components.SlimTooltip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSlimTooltipElementEventMap>(type: K, listener: (this: HTMLSlimTooltipElement, ev: SlimTooltipCustomEvent<HTMLSlimTooltipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSlimTooltipElementEventMap>(type: K, listener: (this: HTMLSlimTooltipElement, ev: SlimTooltipCustomEvent<HTMLSlimTooltipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSlimTooltipElement: {
        prototype: HTMLSlimTooltipElement;
        new (): HTMLSlimTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "slim-alert": HTMLSlimAlertElement;
        "slim-badge": HTMLSlimBadgeElement;
        "slim-button": HTMLSlimButtonElement;
        "slim-checkbox": HTMLSlimCheckboxElement;
        "slim-input": HTMLSlimInputElement;
        "slim-modal": HTMLSlimModalElement;
        "slim-playground-sidebar": HTMLSlimPlaygroundSidebarElement;
        "slim-select": HTMLSlimSelectElement;
        "slim-switch": HTMLSlimSwitchElement;
        "slim-textarea": HTMLSlimTextareaElement;
        "slim-tooltip": HTMLSlimTooltipElement;
    }
}
declare namespace LocalJSX {
    interface SlimAlert {
        "heading"?: string;
        /**
          * @default "info"
         */
        "variant"?: "info" | "success" | "warning" | "danger";
    }
    interface SlimBadge {
        /**
          * @default "md"
         */
        "size"?: "sm" | "md";
        /**
          * @default "neutral"
         */
        "variant"?: "neutral" | "primary" | "success" | "warning" | "danger";
    }
    interface SlimButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary" | "danger" | "ghost";
    }
    interface SlimCheckbox {
        "checkboxId"?: string;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        "onSlimChange"?: (event: SlimCheckboxCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        "value"?: string;
    }
    interface SlimInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "error"?: string;
        "hint"?: string;
        "inputId"?: string;
        "label"?: string;
        "name"?: string;
        "onSlimChange"?: (event: SlimInputCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default "text"
         */
        "type"?: "text" | "email" | "password" | "tel" | "number";
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface SlimModal {
        /**
          * Optional modal title
         */
        "heading"?: string;
        /**
          * Fired when the user requests closing the modal (backdrop click / close button / ESC)
         */
        "onSlimClose"?: (event: SlimModalCustomEvent<void>) => void;
        /**
          * Whether the modal is open
          * @default false
         */
        "open"?: boolean;
    }
    interface SlimPlaygroundSidebar {
        /**
          * Currently active item id.
         */
        "active"?: string;
        /**
          * Whether the sidebar is collapsed (icon-only rail).
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Show/hide the collapse toggle button.
          * @default true
         */
        "collapsible"?: boolean;
        /**
          * Sidebar heading shown in the header.
          * @default "Components"
         */
        "heading"?: string;
        /**
          * Menu items to render.
          * @default []
         */
        "items"?: SlimPlaygroundSidebarItem[];
        /**
          * Emitted when a menu item is selected (detail = item id).
         */
        "onSlimSelect"?: (event: SlimPlaygroundSidebarCustomEvent<string>) => void;
        /**
          * Emitted when the user toggles collapse (detail = next collapsed).
         */
        "onSlimToggle"?: (event: SlimPlaygroundSidebarCustomEvent<boolean>) => void;
        /**
          * @default 24
         */
        "pinnedBottom"?: number;
        /**
          * @default 24
         */
        "pinnedLeft"?: number;
        /**
          * Fixed positioning offsets (in px).
          * @default 24
         */
        "pinnedTop"?: number;
    }
    interface SlimSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        "onSlimChange"?: (event: SlimSelectCustomEvent<string>) => void;
        /**
          * @default []
         */
        "options"?: { value: string; label: string; disabled?: boolean }[];
        /**
          * @default false
         */
        "required"?: boolean;
        "selectId"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface SlimSwitch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        "onSlimChange"?: (event: SlimSwitchCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        "switchId"?: string;
    }
    interface SlimTextarea {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "maxlength"?: number;
        "minlength"?: number;
        "name"?: string;
        "onSlimChange"?: (event: SlimTextareaCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 4
         */
        "rows"?: number;
        "textareaId"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface SlimTooltip {
        /**
          * Disables showing the tooltip via interactions.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Max width of the tooltip bubble, in pixels.
          * @default 240
         */
        "maxWidth"?: number;
        /**
          * Pixel offset between trigger and tooltip bubble.
          * @default 8
         */
        "offset"?: number;
        "onSlimHide"?: (event: SlimTooltipCustomEvent<void>) => void;
        "onSlimShow"?: (event: SlimTooltipCustomEvent<void>) => void;
        /**
          * Controls tooltip visibility. Can be toggled by hover/focus by default.
          * @default false
         */
        "open"?: boolean;
        /**
          * Where the tooltip appears relative to the trigger.
          * @default "top"
         */
        "placement"?: Placement;
        /**
          * Tooltip text. If omitted, the default slot is used as tooltip content.
         */
        "text"?: string;
    }

    interface SlimAlertAttributes {
        "variant": "info" | "success" | "warning" | "danger";
        "heading": string;
    }
    interface SlimBadgeAttributes {
        "variant": "neutral" | "primary" | "success" | "warning" | "danger";
        "size": "sm" | "md";
    }
    interface SlimButtonAttributes {
        "variant": "primary" | "secondary" | "danger" | "ghost";
        "size": "sm" | "md" | "lg";
        "disabled": boolean;
        "loading": boolean;
        "type": "button" | "submit" | "reset";
    }
    interface SlimCheckboxAttributes {
        "label": string;
        "hint": string;
        "error": string;
        "name": string;
        "checked": boolean;
        "value": string;
        "disabled": boolean;
        "required": boolean;
        "checkboxId": string;
    }
    interface SlimInputAttributes {
        "label": string;
        "hint": string;
        "error": string;
        "name": string;
        "value": string;
        "type": "text" | "email" | "password" | "tel" | "number";
        "disabled": boolean;
        "required": boolean;
        "autocomplete": string;
        "inputId": string;
        "placeholder": string;
    }
    interface SlimModalAttributes {
        "open": boolean;
        "heading": string;
    }
    interface SlimPlaygroundSidebarAttributes {
        "heading": string;
        "active": string;
        "collapsed": boolean;
        "collapsible": boolean;
        "pinnedTop": number;
        "pinnedLeft": number;
        "pinnedBottom": number;
    }
    interface SlimSelectAttributes {
        "label": string;
        "hint": string;
        "error": string;
        "name": string;
        "value": string;
        "disabled": boolean;
        "required": boolean;
        "selectId": string;
    }
    interface SlimSwitchAttributes {
        "label": string;
        "hint": string;
        "error": string;
        "name": string;
        "checked": boolean;
        "disabled": boolean;
        "required": boolean;
        "switchId": string;
    }
    interface SlimTextareaAttributes {
        "label": string;
        "hint": string;
        "error": string;
        "name": string;
        "value": string;
        "disabled": boolean;
        "required": boolean;
        "readonly": boolean;
        "placeholder": string;
        "rows": number;
        "maxlength": number;
        "minlength": number;
        "textareaId": string;
    }
    interface SlimTooltipAttributes {
        "text": string;
        "placement": Placement;
        "offset": number;
        "maxWidth": number;
        "disabled": boolean;
        "open": boolean;
    }

    interface IntrinsicElements {
        "slim-alert": Omit<SlimAlert, keyof SlimAlertAttributes> & { [K in keyof SlimAlert & keyof SlimAlertAttributes]?: SlimAlert[K] } & { [K in keyof SlimAlert & keyof SlimAlertAttributes as `attr:${K}`]?: SlimAlertAttributes[K] } & { [K in keyof SlimAlert & keyof SlimAlertAttributes as `prop:${K}`]?: SlimAlert[K] };
        "slim-badge": Omit<SlimBadge, keyof SlimBadgeAttributes> & { [K in keyof SlimBadge & keyof SlimBadgeAttributes]?: SlimBadge[K] } & { [K in keyof SlimBadge & keyof SlimBadgeAttributes as `attr:${K}`]?: SlimBadgeAttributes[K] } & { [K in keyof SlimBadge & keyof SlimBadgeAttributes as `prop:${K}`]?: SlimBadge[K] };
        "slim-button": Omit<SlimButton, keyof SlimButtonAttributes> & { [K in keyof SlimButton & keyof SlimButtonAttributes]?: SlimButton[K] } & { [K in keyof SlimButton & keyof SlimButtonAttributes as `attr:${K}`]?: SlimButtonAttributes[K] } & { [K in keyof SlimButton & keyof SlimButtonAttributes as `prop:${K}`]?: SlimButton[K] };
        "slim-checkbox": Omit<SlimCheckbox, keyof SlimCheckboxAttributes> & { [K in keyof SlimCheckbox & keyof SlimCheckboxAttributes]?: SlimCheckbox[K] } & { [K in keyof SlimCheckbox & keyof SlimCheckboxAttributes as `attr:${K}`]?: SlimCheckboxAttributes[K] } & { [K in keyof SlimCheckbox & keyof SlimCheckboxAttributes as `prop:${K}`]?: SlimCheckbox[K] };
        "slim-input": Omit<SlimInput, keyof SlimInputAttributes> & { [K in keyof SlimInput & keyof SlimInputAttributes]?: SlimInput[K] } & { [K in keyof SlimInput & keyof SlimInputAttributes as `attr:${K}`]?: SlimInputAttributes[K] } & { [K in keyof SlimInput & keyof SlimInputAttributes as `prop:${K}`]?: SlimInput[K] };
        "slim-modal": Omit<SlimModal, keyof SlimModalAttributes> & { [K in keyof SlimModal & keyof SlimModalAttributes]?: SlimModal[K] } & { [K in keyof SlimModal & keyof SlimModalAttributes as `attr:${K}`]?: SlimModalAttributes[K] } & { [K in keyof SlimModal & keyof SlimModalAttributes as `prop:${K}`]?: SlimModal[K] };
        "slim-playground-sidebar": Omit<SlimPlaygroundSidebar, keyof SlimPlaygroundSidebarAttributes> & { [K in keyof SlimPlaygroundSidebar & keyof SlimPlaygroundSidebarAttributes]?: SlimPlaygroundSidebar[K] } & { [K in keyof SlimPlaygroundSidebar & keyof SlimPlaygroundSidebarAttributes as `attr:${K}`]?: SlimPlaygroundSidebarAttributes[K] } & { [K in keyof SlimPlaygroundSidebar & keyof SlimPlaygroundSidebarAttributes as `prop:${K}`]?: SlimPlaygroundSidebar[K] };
        "slim-select": Omit<SlimSelect, keyof SlimSelectAttributes> & { [K in keyof SlimSelect & keyof SlimSelectAttributes]?: SlimSelect[K] } & { [K in keyof SlimSelect & keyof SlimSelectAttributes as `attr:${K}`]?: SlimSelectAttributes[K] } & { [K in keyof SlimSelect & keyof SlimSelectAttributes as `prop:${K}`]?: SlimSelect[K] };
        "slim-switch": Omit<SlimSwitch, keyof SlimSwitchAttributes> & { [K in keyof SlimSwitch & keyof SlimSwitchAttributes]?: SlimSwitch[K] } & { [K in keyof SlimSwitch & keyof SlimSwitchAttributes as `attr:${K}`]?: SlimSwitchAttributes[K] } & { [K in keyof SlimSwitch & keyof SlimSwitchAttributes as `prop:${K}`]?: SlimSwitch[K] };
        "slim-textarea": Omit<SlimTextarea, keyof SlimTextareaAttributes> & { [K in keyof SlimTextarea & keyof SlimTextareaAttributes]?: SlimTextarea[K] } & { [K in keyof SlimTextarea & keyof SlimTextareaAttributes as `attr:${K}`]?: SlimTextareaAttributes[K] } & { [K in keyof SlimTextarea & keyof SlimTextareaAttributes as `prop:${K}`]?: SlimTextarea[K] };
        "slim-tooltip": Omit<SlimTooltip, keyof SlimTooltipAttributes> & { [K in keyof SlimTooltip & keyof SlimTooltipAttributes]?: SlimTooltip[K] } & { [K in keyof SlimTooltip & keyof SlimTooltipAttributes as `attr:${K}`]?: SlimTooltipAttributes[K] } & { [K in keyof SlimTooltip & keyof SlimTooltipAttributes as `prop:${K}`]?: SlimTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "slim-alert": LocalJSX.IntrinsicElements["slim-alert"] & JSXBase.HTMLAttributes<HTMLSlimAlertElement>;
            "slim-badge": LocalJSX.IntrinsicElements["slim-badge"] & JSXBase.HTMLAttributes<HTMLSlimBadgeElement>;
            "slim-button": LocalJSX.IntrinsicElements["slim-button"] & JSXBase.HTMLAttributes<HTMLSlimButtonElement>;
            "slim-checkbox": LocalJSX.IntrinsicElements["slim-checkbox"] & JSXBase.HTMLAttributes<HTMLSlimCheckboxElement>;
            "slim-input": LocalJSX.IntrinsicElements["slim-input"] & JSXBase.HTMLAttributes<HTMLSlimInputElement>;
            "slim-modal": LocalJSX.IntrinsicElements["slim-modal"] & JSXBase.HTMLAttributes<HTMLSlimModalElement>;
            "slim-playground-sidebar": LocalJSX.IntrinsicElements["slim-playground-sidebar"] & JSXBase.HTMLAttributes<HTMLSlimPlaygroundSidebarElement>;
            "slim-select": LocalJSX.IntrinsicElements["slim-select"] & JSXBase.HTMLAttributes<HTMLSlimSelectElement>;
            "slim-switch": LocalJSX.IntrinsicElements["slim-switch"] & JSXBase.HTMLAttributes<HTMLSlimSwitchElement>;
            "slim-textarea": LocalJSX.IntrinsicElements["slim-textarea"] & JSXBase.HTMLAttributes<HTMLSlimTextareaElement>;
            "slim-tooltip": LocalJSX.IntrinsicElements["slim-tooltip"] & JSXBase.HTMLAttributes<HTMLSlimTooltipElement>;
        }
    }
}
