'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SlimAlert as SlimAlertElement, defineCustomElement as defineSlimAlert } from "@slimkhemiri/web-components/dist/components/slim-alert.js";
import { SlimBadge as SlimBadgeElement, defineCustomElement as defineSlimBadge } from "@slimkhemiri/web-components/dist/components/slim-badge.js";
import { SlimButton as SlimButtonElement, defineCustomElement as defineSlimButton } from "@slimkhemiri/web-components/dist/components/slim-button.js";
import { SlimCheckbox as SlimCheckboxElement, defineCustomElement as defineSlimCheckbox } from "@slimkhemiri/web-components/dist/components/slim-checkbox.js";
import { SlimInput as SlimInputElement, defineCustomElement as defineSlimInput } from "@slimkhemiri/web-components/dist/components/slim-input.js";
import { SlimModal as SlimModalElement, defineCustomElement as defineSlimModal } from "@slimkhemiri/web-components/dist/components/slim-modal.js";
import { SlimPlaygroundSidebar as SlimPlaygroundSidebarElement, defineCustomElement as defineSlimPlaygroundSidebar } from "@slimkhemiri/web-components/dist/components/slim-playground-sidebar.js";
import { SlimSelect as SlimSelectElement, defineCustomElement as defineSlimSelect } from "@slimkhemiri/web-components/dist/components/slim-select.js";
import { SlimSwitch as SlimSwitchElement, defineCustomElement as defineSlimSwitch } from "@slimkhemiri/web-components/dist/components/slim-switch.js";
import { SlimTextarea as SlimTextareaElement, defineCustomElement as defineSlimTextarea } from "@slimkhemiri/web-components/dist/components/slim-textarea.js";
import { SlimTooltip as SlimTooltipElement, defineCustomElement as defineSlimTooltip } from "@slimkhemiri/web-components/dist/components/slim-tooltip.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type SlimAlertEvents = NonNullable<unknown>;

export const SlimAlert: StencilReactComponent<SlimAlertElement, SlimAlertEvents> = /*@__PURE__*/ createComponent<SlimAlertElement, SlimAlertEvents>({
    tagName: 'slim-alert',
    elementClass: SlimAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SlimAlertEvents,
    defineCustomElement: defineSlimAlert
});

type SlimBadgeEvents = NonNullable<unknown>;

export const SlimBadge: StencilReactComponent<SlimBadgeElement, SlimBadgeEvents> = /*@__PURE__*/ createComponent<SlimBadgeElement, SlimBadgeEvents>({
    tagName: 'slim-badge',
    elementClass: SlimBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SlimBadgeEvents,
    defineCustomElement: defineSlimBadge
});

type SlimButtonEvents = NonNullable<unknown>;

export const SlimButton: StencilReactComponent<SlimButtonElement, SlimButtonEvents> = /*@__PURE__*/ createComponent<SlimButtonElement, SlimButtonEvents>({
    tagName: 'slim-button',
    elementClass: SlimButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SlimButtonEvents,
    defineCustomElement: defineSlimButton
});

type SlimCheckboxEvents = { onSlimChange: EventName<CustomEvent<boolean>> };

export const SlimCheckbox: StencilReactComponent<SlimCheckboxElement, SlimCheckboxEvents> = /*@__PURE__*/ createComponent<SlimCheckboxElement, SlimCheckboxEvents>({
    tagName: 'slim-checkbox',
    elementClass: SlimCheckboxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSlimChange: 'slimChange' } as SlimCheckboxEvents,
    defineCustomElement: defineSlimCheckbox
});

type SlimInputEvents = { onSlimChange: EventName<CustomEvent<string>> };

export const SlimInput: StencilReactComponent<SlimInputElement, SlimInputEvents> = /*@__PURE__*/ createComponent<SlimInputElement, SlimInputEvents>({
    tagName: 'slim-input',
    elementClass: SlimInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSlimChange: 'slimChange' } as SlimInputEvents,
    defineCustomElement: defineSlimInput
});

type SlimModalEvents = { onSlimClose: EventName<CustomEvent<void>> };

export const SlimModal: StencilReactComponent<SlimModalElement, SlimModalEvents> = /*@__PURE__*/ createComponent<SlimModalElement, SlimModalEvents>({
    tagName: 'slim-modal',
    elementClass: SlimModalElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSlimClose: 'slimClose' } as SlimModalEvents,
    defineCustomElement: defineSlimModal
});

type SlimPlaygroundSidebarEvents = {
    onSlimSelect: EventName<CustomEvent<string>>,
    onSlimToggle: EventName<CustomEvent<boolean>>
};

export const SlimPlaygroundSidebar: StencilReactComponent<SlimPlaygroundSidebarElement, SlimPlaygroundSidebarEvents> = /*@__PURE__*/ createComponent<SlimPlaygroundSidebarElement, SlimPlaygroundSidebarEvents>({
    tagName: 'slim-playground-sidebar',
    elementClass: SlimPlaygroundSidebarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onSlimSelect: 'slimSelect',
        onSlimToggle: 'slimToggle'
    } as SlimPlaygroundSidebarEvents,
    defineCustomElement: defineSlimPlaygroundSidebar
});

type SlimSelectEvents = { onSlimChange: EventName<CustomEvent<string>> };

export const SlimSelect: StencilReactComponent<SlimSelectElement, SlimSelectEvents> = /*@__PURE__*/ createComponent<SlimSelectElement, SlimSelectEvents>({
    tagName: 'slim-select',
    elementClass: SlimSelectElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSlimChange: 'slimChange' } as SlimSelectEvents,
    defineCustomElement: defineSlimSelect
});

type SlimSwitchEvents = { onSlimChange: EventName<CustomEvent<boolean>> };

export const SlimSwitch: StencilReactComponent<SlimSwitchElement, SlimSwitchEvents> = /*@__PURE__*/ createComponent<SlimSwitchElement, SlimSwitchEvents>({
    tagName: 'slim-switch',
    elementClass: SlimSwitchElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSlimChange: 'slimChange' } as SlimSwitchEvents,
    defineCustomElement: defineSlimSwitch
});

type SlimTextareaEvents = { onSlimChange: EventName<CustomEvent<string>> };

export const SlimTextarea: StencilReactComponent<SlimTextareaElement, SlimTextareaEvents> = /*@__PURE__*/ createComponent<SlimTextareaElement, SlimTextareaEvents>({
    tagName: 'slim-textarea',
    elementClass: SlimTextareaElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSlimChange: 'slimChange' } as SlimTextareaEvents,
    defineCustomElement: defineSlimTextarea
});

type SlimTooltipEvents = {
    onSlimShow: EventName<CustomEvent<void>>,
    onSlimHide: EventName<CustomEvent<void>>
};

export const SlimTooltip: StencilReactComponent<SlimTooltipElement, SlimTooltipEvents> = /*@__PURE__*/ createComponent<SlimTooltipElement, SlimTooltipEvents>({
    tagName: 'slim-tooltip',
    elementClass: SlimTooltipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onSlimShow: 'slimShow',
        onSlimHide: 'slimHide'
    } as SlimTooltipEvents,
    defineCustomElement: defineSlimTooltip
});
